board_game/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "board_games"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('board_games.urls')),
]

board_games/urls.py
"""Defines URL patterns for board_games."""
from django.urls import path
from . import views

app_name = "board_games"

urlpatterns = [
    # Home page
    path ('', views.index, name='index'),

    # Page that shows all board games
    path('games/', views.games, name='games'),

    # Detail page for a single board game
    path('games/<int:game_id>/', views.game, name='game'),

    # Page for adding a new board game
    path('new_game/', views.new_game, name='new_game'),

    # Page for adding a description
    path('new_description/<int:game_id>/', views.new_description, name='new_description'),

    # Page for editing a description
    path('edit_description/<int:description_id>/', views.edit_description, name='edit_description'),

    # Page for adding a loaner
    path('new_loaner/<int:game_id>/', views.new_loaner, name='new_loaner'),

    # Page for editing a loaner
    path('return_game/<int:loaner_id>/', views.return_game, name='return_game'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

board_games/models.py
from django.core.exceptions import DisallowedHost
from django.db import models
from django.contrib.auth.models import User #-emilia

# Create your models here.

class Game(models.Model):
    """A board game"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    owner = models.ForeignKey(User, on_delete=models.CASCADE) #-emilia

class Description(models.Model):
    """Description of a board game"""
    game = models.ForeignKey(Game, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'descriptions'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

class Loaner(models.Model):
    """Loaner of a board game"""
    game = models.ForeignKey(Game, on_delete = models.CASCADE)
    text = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'loaners'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

board_games/forms.py
from django import forms

from .models import Game, Description, Loaner

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['text']
        labels = {'text': ''}

class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

class LoanerForm(forms.ModelForm):
    class Meta:
        model = Loaner
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':25, 'rows':1})}

board_games/views.py
from django.shortcuts import render, redirect


from .models import Game, Description, Loaner
from .forms import GameForm, DescriptionForm, LoanerForm
from django.contrib.auth.decorators import login_required  # -emilia
from django.http import HttpResponseRedirect, Http404


# Create your views here.

def index (request):
    """The home page for Board Games"""
    return render(request, 'board_games/index.html')


def games(request):
    """Show all games"""
    games = Game.objects.order_by('date_added')
    context = {'games': games}
    return render(request, 'board_games/games.html', context)

def game(request, game_id):
    """Show a single board game and its description."""
    game = Game.objects.get(id=game_id)
    descriptions = game.description_set.order_by('-date_added')
    loaners = game.loaner_set.order_by('-date_added')
    context = {'game': game, 'descriptions': descriptions, 'loaners': loaners}
    return render(request, 'board_games/game.html', context)

@login_required
def new_game(request):
    """Add a new game."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = GameForm()
    else:
        # POST data submitted; process data.
        form = GameForm(data=request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.owner = request.user
            new_game.save()
            return redirect('board_games:games')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'board_games/new_game.html', context)

@login_required
def new_description(request, game_id):
    """Add a new description for a partular board game."""
    game = Game.objects.get(id=game_id)

    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = DescriptionForm()
    else:
        # POST data submitted, process data.
        form = DescriptionForm(data=request.POST)
        if form.is_valid():
            new_description = form.save(commit=False)
            new_description.game = game
            new_description.save()
            return redirect('board_games:game', game_id=game_id)
    
    # Display a blank or invalid form.
    context = {'game': game, 'form': form}
    return render(request, 'board_games/new_description.html', context)

@login_required
def edit_description(request, description_id):
    """Edit an existing description."""
    description = Description.objects.get(id=description_id)
    game = description.game
    if game.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current description.
        form = DescriptionForm(instance=description)
    else:
        # POST data submitted; process data.
        form = DescriptionForm(instance=description, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('board_games:game', game_id=game.id)
    
    context = {'description': description, 'game': game, 'form': form}
    return render(request, 'board_games/edit_description.html', context)


@login_required
def new_loaner(request, game_id):
    """Add a new description for a partular board game."""
    game = Game.objects.get(id=game_id)

    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = LoanerForm()
    else:
        # POST data submitted, process data.
        form = LoanerForm(data=request.POST)

        if form.is_valid():
            new_loaner = form.save(commit=False)
            new_loaner.game = game
            new_loaner.save()

            return redirect('board_games:game', game_id=game_id)
    
    # Display a blank or invalid form.
    context = {'game': game, 'form': form}
    return render(request, 'board_games/new_loaner.html', context)

@login_required
def return_game(request, loaner_id):
    """Edit an existing description."""
    loaner = Loaner.objects.get(id=loaner_id)
    game = loaner.game
    if game.owner != request.user:
        raise Http404

    instance = Loaner.objects.get(id=loaner_id)
    instance.delete()

    context = {'loaner': loaner, 'game': game}
    return render(request, 'board_games/return_game.html', context)


#def edit_loaner(request):
#    instance = Loaner.objects.get(id=id)
#    instance.delete()
#
#    context = {'instance': instance}
#    return render(request, 'board_games/game.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('board_games:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

board_games/templates/board_games/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Board Games</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'board_games:index'%}">Board Games</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board_games:games'%}">Existing Board Games</a>
                </li>
                {% else %}
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text"}">Hello, {{ user.username }}!</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      
      <main role="main" class="container">
          <div class="pb-2 mb-2 border-bottom">
              {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

board_games/templates/board_games/edit_description.html
{% extends "board_games/base.html" %}

{% block content %}

  <p><a href="{% url 'board_games:game' game.id %}">{{ game }}</a></p>

  <p>Edit description:</p>

  <form action="{% url 'board_games:edit_description' description.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

board_games/templates/board_games/game.html
{% extends 'board_games/base.html' %}

{% block page_header %}
  <h3>{{ game }}</h3>
{% endblock page_header %}

{% block content %}

  {% for loaner in loaners %}
      Game is being loaned by:{{ loaner.text|linebreaks }} 
      since: {{ loaner.date_added|date:'M d, Y H:i' }}
      <a href="{% url 'board_games:return_game' loaner.id %}">Return game</a>

  {% empty %}
    <p>There are no loaners for this board game yet.</p>
    <a href="{% url 'board_games:new_loaner' game.id %}">Add new loaner</a>
  {% endfor %}

    {% for description in descriptions %}
      <div class="card mb-3">
        <h4 class="card-header">
          {{ description.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'board_games:edit_description' description.id %}">
            Edit description</a></small>
        </h4>
        <div class="card-body">
          {{ description.text|linebreaks }}
        </div>
      </div>
    {% empty %}
      <p>There is no description for this board game yet.</p>
      <small><a href="{% url 'board_games:new_description' game.id %}">
        Add new description</a></small>
    {% endfor %}

{% endblock content %}

board_games/templates/board_games/games.html
{% extends "board_games/base.html" %}

{% block page_header %}
  <h1>Board Games</h1> <h6><a href="{% url 'board_games:new_game' %}">Add a new board game</a></h6>
{% endblock page_header %}

{% block content %}

{% for game in games %}
      <div class="card mb-3">
        <h4 class="card-header">
          <small><a href="{% url 'board_games:game' game.id %}">{{ game }}</a>
        </h4>
      </div>
    {% empty %}
      <p>No games have been added yet.</p>
    {% endfor%}
      
  

{% endblock content %}

board_games/templates/board_games/index.html
{% extends "board_games/base.html" %}

{% block page_header %}
  <div class="jumbotron">
      <h1 class="display-3">Step in to the world of board games.</h1>

      <p class="lead"> Add your board games to the site, add descriptions to them, 
          and keep track of the loans.</p>

      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'board_games:games'%}">See which board games are available</a>
      {% else %}
      <a class="btn btn-lg btn-primary"href="{% url 'users:login' %}"
            role="button">Log in &raquo;</a>
    
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
      {% endif %}
  </div>
{% endblock page_header %}

board_games/templates/board_games/new_description.html
{% extends "board_games/base.html" %}

{% block content %}

<p><a href="{% url 'board_games:new_description' game.id %}">{{ game }}</a></p>

<p>Add a description:</p>
<form action="{% url 'board_games:new_description' game.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Add description</button>
</form>

{% endblock content %}

board_games/templates/board_games/new_game.html
{% extends "board_games/base.html" %}

{% block content %}
  <p>Add a new board game:</p>

  <form action="{% url 'board_games:new_game' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add game</button>
  </form>

{% endblock content %}

board_games/templates/board_games/new_loaner.html
{% extends "board_games/base.html" %}

{% block content %}
<p><a href="{% url 'board_games:new_loaner' game.id %}">{{ game }}</a></p>

<p>Add a loaner:</p>
<form action="{% url 'board_games:new_loaner' game.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Loan</button>
</form>

{% endblock content %}

board_games/templates/board_games/return_game.html
{% extends "board_games/base.html" %}

{% block content %}

  <p><a href="{% url 'board_games:game' game.id %}">You have returned {{ game }}</a></p>

{% endblock content %}